on: 
  pull_request:
    types: [opened]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to generate & validate code coverage
    steps:
      - name: Code coverage action step
        id: code_coverage
        uses: wesfdev/my-cc-g-action@v1.5
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}