on: 
  pull_request:
    types: [opened]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - name: Hello world action step
        id: hello
        uses: wesfdev/my-cc-g-action@v1.1
        with:
          who-to-greet: 'Wes'
      # Use the output from the `hello` step
      - name: Get the output time
        run: echo "The time was ${{ steps.hello.outputs.time }}"
